### ISSUE TITLE
3.x support

### ISSUE THREAD

**Issue by Eeems** [matteodelabre/toltec#820]
### Current Status

- [x] ~rm2fb does not support 3.x~ rm2fb now supports up to 3.3.2
- [x] Installer doesn't warn users that they are installing on an unsupported OS version (#445)
  - Will be fixed by #759
- [x] There is no way to make packages only available on certain OS versions (#701)
   - Will be fixed by #759
- [x] ddvk-hacks should be removed on upgrade to 3.x (#578 )
  - Will be fixed by #759
- [x] Kernel modules should be removed on upgrade to 3.x (#506)
  - Will be fixed by #759
- [x] Install broken on 3.6+ due to issue with wget (#731)
  - Will be fixed by #751
- [x] sync.service renamed to rm-sync.service in OS 3.5+ (#717)
  - Will be fixed by #718
- [x] Full test of all the packages on 3.x to ensure we aren't missing any other issues
  - [x] 7zip
  - [x] appmarkable
  - [x] aspnet-runtime
  - [x] aspnet-targeting-pack
  - [x] bash-completion
  - [x] bottom
  - [x] bufshot
  - [x] calculator
  - [x] changescrn
  - [x] chessmarkable
  - [x] display
  - [x] doomarkable
  - [x] dotnet-host
  - [x] dotnet-profile
  - [x] dotnet-runtime
  - [x] dotnet-sdk
  - [x] dotnet-targeting-pack
  - [x] draft
  - [x] dumbskull
  - [x] entware-rc
  - [x] evtest
  - [x] fbdepth
  - [x] fbink
  - [x] fbink-doom - this doesn't appear to display anything on the rM2 #856
  - [x] fingerterm
  - [x] folly
  - [x] genie
  - [x] ~~gocryptfs~~ - depends on fuse which was removed #852
  - [x] harmony
  - [x] iago
  - [x] inject_evdev
  - [x] ~~innernet-client~~ - depends on wireguard which was removed #852
  - [x] kernelctl
  - [x] keywriter
  - [x] koreader
  - [x] lamp
  - [x] launcherctl - #857
  - [x] lf
  - [x] libdlib
  - [x] libdlib-dev - No way to test on device, used for build of recrossable
  - [x] libsentry
  - [x] libvncclient
  - [x] libvncserver - No way to test on device currently
  - [x] libvncserver-dev - No way to test on device, used for build of vnsee
  - [x] ~~linux-mainline~~ - Soft-bricks device #852
  - [x] linux-stracciatella
  - [x] micro
  - [x] mines
  - [x] mmc-utils
  - [x] move-logs-to-opt
  - [x] nao
  - [x] neofetch
  - [x] netevent
  - [x] netstandard-targeting-pack
  - [x] netsurf
  - [x] open-remarkable-shutdown - this apparently hasn't worked on rM2 ever, but nobody has reported it #854
  - [x] oxide
  - [x] oxide-extra
  - [x] oxide-utils
  - [x] plato
  - [x] puzzles
  - [x] quickjs
  - [x] reboot-guard
  - [x] recrossable
  - [x] regenda
  - [x] remarkable-splash
  - [x] remarkable-stylus - Depends on ddvk-hacks to work, will be removed until rm-hacks is added #855
  - [x] remux
  - [x] restream
  - [x] reterm
  - [x] retris
  - [x] ripgrep
  - [x] rm2-suspend-fix
  - [x] rm2fb-client
  - [x] rmfakecloud-proxy
  - [x] rmfm
  - [x] rmservewacominput
  - [x] rpncalc
  - [x] signature-rm
  - [x] sill
  - [x] simple
  - [x] sudoku
  - [x] tailscale-systemd
  - [x] templatectl
  - [x] tilem
  - [x] toltec-completion
  - [x] vnsee
  - [x] webinterface-localhost
  - [x] webinterface-onboot
  - [x] webinterface-upload-button
  - [x] webinterface-wifi
  - [x] whiteboard-hypercard
  - [x] wikipedia
  - [x] wordlet
  - [x] xochitl
  - [x] yaft
  - [x] zoneinfo-utils
  - [x] zerotier-one
  - [x] zshelf - Loads, but application appears to be broken by default and there are not clear instructions on how to get it to work. It may be worth dropping support.

There are other PRs that are waiting on 3.x support in https://github.com/toltec-dev/toltec/milestone/7, but they are not required for 3.x support.

### Timeline

There is no timeline. This will be done when it is done. This is all volunteer work and depends on how fast we can get people to test and approve pull requests.

**Comment by gullradriel** [comment]
rm2fb now supports up to 3.8.2 ! :-)

**Comment by Eeems** [comment]
> rm2fb now supports up to 3.8.2 ! :-)

There has been no rm2fb release yet. The official version still only supports 3.3.2: https://github.com/ddvk/remarkable2-framebuffer/releases

**Comment by sasdallas** [comment]
So, 3.x support only will go up to 3.3.2 because of rm2fb?

**Comment by Eeems** [comment]
> So, 3.x support only will go up to 3.3.2 because of rm2fb?

For now. A lot more work and testing is required for later versions as well. 3.6 updated glibc, 3.9 update Qt to a new major version. All of it requires sorting out a rm2fb solution, and if that requires using a fork of rm2fb that doesn't have backwards compatibility, a new repository split would be required, which means we need to test the upgrade path properly.

**Comment by Muathics** [comment]
So when can I install Koreader via it in Remarkable 1 with version 3.8? Thanks!

**Comment by Eeems** [comment]
> So when can I install Koreader via it in Remarkable 1 with version 3.8? Thanks!

There is no timeline. It'll be done when it's done.

**Comment by Muathics** [comment]
> > So when can I install Koreader via it in Remarkable 1 with version 3.8? Thanks!
> 
> There is no timeline. It'll be done when it's done.

Thank you!

**Comment by jkesselm** [comment]
MANY thanks for the status update!

**Comment by Eeems** [comment]
All that is remaining is a full test of all packages in the testing branch while on 3.3.2. I'll add a list of all the packages to test that will be used to keep track of the status soon.

**Comment by Eeems** [comment]
- [ ] 7zip
- [ ] appmarkable
- [ ] aspnet-runtime
- [ ] aspnet-targeting-pack
- [ ] bash-completion
- [ ] bottom
- [ ] bufshot
- [ ] calculator
- [ ] changescrn
- [ ] chessmarkable
- [ ] display
- [ ] doomarkable
- [ ] dotnet-host
- [ ] dotnet-profile
- [ ] dotnet-runtime
- [ ] dotnet-sdk
- [ ] dotnet-targeting-pack
- [ ] draft
- [ ] dumbskull
- [ ] evtest
- [ ] fbdepth
- [ ] fbink
- [ ] fbink-doom
- [ ] fingerterm
- [ ] folly
- [ ] genie
- [ ] gocryptfs
- [ ] harmony
- [ ] iago
- [ ] inject_evdev
- [ ] innernet-client
- [ ] kernelctl
- [ ] keywriter
- [ ] koreader
- [ ] lamp
- [ ] lf
- [ ] libdblib
- [ ] libdlib-dev
- [ ] libsentry
- [ ] libvncclient
- [ ] libvncserver
- [ ] libvncserver-dev
- [ ] linux-mainline
- [ ] linux-stracciatella
- [ ] micro
- [ ] mines
- [ ] mmc-utils
- [ ] move-logs-to-opt
- [ ] nao
- [ ] neofetch
- [ ] netevent
- [ ] netstandard-targeting-pack
- [ ] netsurf
- [ ] open-remarkable-shutdown
- [ ] oxide
- [ ] oxide-extra
- [ ] oxide-utils
- [ ] plato
- [ ] puzzles
- [ ] quickjs
- [ ] reboot-guard
- [ ] recrossable
- [ ] regenda
- [ ] remarkable-splash
- [ ] remarkable-stylus
- [ ] remux
- [ ] restream
- [ ] reterm
- [ ] retris
- [ ] ripgrep
- [ ] rm2-suspend-fix
- [ ] rm2fb-client
- [ ] rmfakecloud-proxy
- [ ] rmfm
- [ ] rmservewacominput
- [ ] rpncalc
- [ ] signature-rm
- [ ] sill
- [ ] simple
- [ ] sudoku
- [ ] tailscale-systemd
- [ ] templatectl
- [ ] tilem
- [ ] toltec-completion
- [ ] vnsee
- [ ] webinterface-localhost
- [ ] webinterface-onboot
- [ ] webinterface-upload-button
- [ ] webinterface-wifi
- [ ] whiteboard-hypercard
- [ ] wikipedia
- [ ] wordlet
- [ ] xochitl
- [ ] yaft
- [ ] zoneinfo-utils
- [ ] zshelf

**Comment by Eeems** [comment]
Testing is done. There are a couple of pull requests that need to be merged, and then this is ready to go in the next stable merge.

**Comment by StarNumber12046** [comment]
Tested tailscale-systemd, it works

**Comment by Eeems** [comment]
New stable merge PR is pending validation and approval. The earliest this will be merged is Monday. Due to turnaround times on getting PRs approved though, this may be longer.
